### PR TITLE
markdown syntax fixes

### PR DESCRIPTION
**Pull request by larsks**
Several documents in the docs/ subdirectory had Markdown syntax errors that prevented the documents displaying correctly on github.  This isn't a comprehensive set of patches but it's a start.

### CODE REVIEW

**Comment by pascallanger** [comment]
Thanks

**Comment by larsks** [comment]
Uh...you're welcome, but I'm curious why you didn't merge this. Did I screw something up?

**Comment by pascallanger** [comment]
2 persons have submitted an equivalent pull request if I'm not wrong... So I've pulled the first one but there was no point applying the second one.
Let me know if your change is not there...

**Comment by larsks** [comment]
There are still many changes in this PR that are not in `master`.  E.g., take a look at [Compiling.md in `master`](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling.md) vs. [Compiling.md in this PR](https://github.com/larsks/DIY-Multiprotocol-TX-Module/blob/729b85e928748da90bcfb3d59de5f2915cd10be9/docs/Compiling.md).

**Pull request closed without merging**
