### PR TITLE
Initial Version of CloneMode

### PR DESCRIPTION
**Pull request by E1yot**
- Bind an FRSKY_X Transmitter with RX-Number 15 (Should be changed to 63, but I'm on OTX2.2.x at the moment and there is 15 the highest RX-Number) to your secondary TX using Multimodule in FRSKY-RX mode.
- Use a secondary TX to create (or copy) a model using Multimodule in FRSKY-TX mode and use the RX-Number of the model in the original TX
Now you can use both transmitters without rebinding the RX

It's useful, if you have a full size TX like Taranis or Horus and a second lightweight TX like XLite.

### CODE REVIEW

**Comment by pascallanger** [comment]
I like your proposed change. I've commented the code where I could see it done differently. I'm fine to implement them myself if you want.
Also the protocol_details.md file has to be updated with the new functionnality.

**Comment by benlye** [comment]
Will we need to add a page to the documentation site?  Can someone give me step-by-step instructions so I can start a draft?

**Comment by pascallanger** [comment]
This is my understanding by looking at the code change and my proposed suggestions.
Clone mode operation:
- Select the FrSkyRX protocol, subprotocol CloneTX
- Place both the orginal TX and multi in bind mode
- Wait for the bind to complete
- From there the FrSkyD / FrSkyX protocol will now clone the original TX

Notes:
- For FrSkyD, only the RX number used during bind is cloned -> you can't use RX num anymore
- For FrSkyX, RX number has to be adjusted on each model to match the original TX model
- Once the clone mode is activated the FrSkyD and FrSkyX protocols will use the clone mode only. If you want to disable the clone mode, you need to redo the bind with the FrSkyRX protocol and subprotocol RX.

**Comment by pascallanger** [comment]
I've just pushed a new version 1.3.0.85.
Please test and let me know if it works as intended. Documentation: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#frsky_rx---55
Pascal

**Pull request merged**
