### PR TITLE
Protocol Flysky AFHDS2A receiver

### PR DESCRIPTION
**Pull request by goebish**
Add Flysky AFHDS2A receiver protocol to be used as a wireless training "cable" by OpenTX 2.3+

Protocol#: 56
option: frequency fine tune (usually not required)
low power mode: disable lna

### CODE REVIEW

**Comment by pascallanger** [comment]
Excellent thanks

**Comment by benlye** [comment]
Disabling the CC2500 module causes a compilation error in AFHDS2A_Rx_a7105.ino:
`AFHDS2A_Rx_a7105:72:54: error: 'CC2500_SetTxRxMode' was not declared in this scope`

It looks like you're referencing a CC2500 function on lines 76 and 108:

**Comment by pascallanger** [comment]
Thanks! it's fixed.
Do you know why Travis was not complaining?

**Comment by benlye** [comment]
We don't do any tests with RF modules completely disabled - we only disable individual protocols.  I'll add individual tests for each RF component so that we catch things like this in the future.

I only spotted it because when I want to do quick manual tests for AVR I disable the CC2500 and NRF24L01 to make it fit.

**Comment by goebish** [comment]
Thanks for noticing, bad copy paste ...

**Pull request merged**
