### PR TITLE
Multi telemetry v2

### PR DESCRIPTION
**Pull request by schwabe**
- Implement status output on uart1 for stm32
- Implement telemetry to report sync status to allow TX to sync its output
- replace hardcoded eeprom offsets with documented constats
- implement multi commands
  - allows enabling/disabling sync from remote
  - allows choose inversion on/off on STM32

### CODE REVIEW

**Comment by schwabe** [comment]
Since I initially proposed these changes you seem to have manually cherry picked some one them. I updated the pull request to apply cleanly on master again.

**Comment by pascallanger** [comment]
Arne, can you wait before I port you changes over. I'm doing a lot of modifications right now to the main code.

**Comment by schwabe** [comment]
@pascallanger Too late now ;)

**Comment by OpenUAS** [comment]
Where can we help to make this PR go through? Could easily rebase it on current master and test.

Otherwise if the idea is not OK maybe close the PR?

**Pull request closed without merging**
