### PR TITLE
Hubsan updates

### PR DESCRIPTION
**Pull request by powercycle**
This is my first attempt at matching up the Hubsan protocol from goebish - repo.  Unfortunately, I don't have a receiver to test these changes on.

### CODE REVIEW

**Comment by dperry20** [comment]
Is this for taranis OpenTx?

**Comment by powercycle** [comment]
Attempting to convert goebish code for use on multi-module., If you have a 501, 301 or 107, would you be willing to test it?

**Comment by dperry20** [comment]
I don't mind trying it out on the Hubsan 502s. I also have the 501

Danny

------ Original Message ------

**Comment by dperry20** [comment]
Yes I saw that and I wasn't sure if it was for the Devo or Taranis.

Why do you use the name powercycle?

Danny

------ Original Message ------

**Comment by powercycle** [comment]
Don't believe the 502's will work, at least this isn't written specifically for it that I am aware of.   
Got tired of power cycling my windows machines because of unexplained issues...moved to linux.

**Comment by dperry20** [comment]
I have used the same Hubsan controller for both

------ Original Message ------

**Comment by powercycle** [comment]
Look forward to your report.

**Comment by dperry20** [comment]
So tell me what exactly will I be doing.

I will open up the 4in1 module file in arduino. Make the changes that I 
saw for the hubsan protocol. I save it and upload it into the 4in1 
module.

The config.h file remains the same.


You are going to have to walk me through a little

thanks

------ Original Message ------

**Comment by powercycle** [comment]
If you get stuck, best place to ask questions is RCgroups, but the Compiling instructions are pretty detailed and should give you what you need.

**Comment by powercycle** [comment]
If you get stuck, best place to ask questions is RCgroups, but the Compiling instructions are pretty detailed and should give you what you need.

**Comment by powercycle** [comment]
Danny, 
Any success in using this?

**Comment by dperry20** [comment]
I hope you had a pleasant trip.
As per our last email, I stated that the code may have had some bugs in 
it. I am not a programmer. The only programming I did was in Fortran in 
my younger days. I did make some correction that allowed me to upload 
the hubsan.ino file. Neither the telemetry nor the functions worked for 
me.

Thanks for getting back to me.

Danny

------ Original Message ------

**Comment by powercycle** [comment]
Did it bind? I haven't traded any e-mails with you recently, so not sure what you are referring to.

**Comment by dperry20** [comment]
It did bind. Sorry I traded emails with pascallanger

**Comment by dperry20** [comment]
I can email you the ino file with changes I made

**Comment by powercycle** [comment]
@dperry20 ,
I just checked the branch and it compiles without issue, can you please use my _Config.h and the branch and tell me how many bytes the sketch uses.  You will have to rename it and put it it in the correct directory.
[_Config.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/852823/_Config.txt)

**Comment by dperry20** [comment]
I can do that first of the week. 

Danny

**Comment by dperry20** [comment]
Do you have a hubsan 501 or 502 drone. 

Danny

**Comment by powercycle** [comment]
Unfortunately no, which is why I need your help with testing the updates.

**Pull request closed without merging**
