### PR TITLE
Add Silverware's analog aux channel feature to Bayang protocol

### PR DESCRIPTION
**Pull request by brianquad**
This change to the Bayang protocol adds an option to steal two presently unused (by the Silverware firmware, which targets several Bayang quads) in the protocol to send two more "analog" (non-binary) channels of data to the Rx. With corresponding changes on the Rx firmware, those new aux channels can be used to do more interesting things than the other binary aux channels. Some users have really liked PID tuning with the extra channels.

More information on the Silverware additions here:
https://www.rcgroups.com/forums/showthread.php?3121896-Analog-Aux-Channels-for-Silverware

The main NFE Silverware fork now has this feature available:
https://github.com/NotFastEnuf/NFE_Silverware

I am making a corresponding pull request to Deviation Tx with the same additions to the Bayang protocol.

### CODE REVIEW

**Comment by brianquad** [comment]
FYI, the Travis build is failing on the E01X_NRF24L01 file (which I didn't touch):

> Building E01X_NRF24L01_INO
> Picked up JAVA_TOOL_OPTIONS: 
> Loading configuration...
> Initializing packages...
> Preparing boards...
> Verifying...
> /home/travis/build/pascallanger/DIY-Multiprotocol-TX-Module/Multiprotocol/E01X_nrf24l01.ino: In function 'void E01X_send_packet(uint8_t)':
> E01X_nrf24l01:221: error: 'BV' was not declared in this scope
>    XN297_Configure(BV(NRF24L01_00_EN_CRC) | BV(NRF24L01_00_CRCO) | BV(NRF24L01_00_PWR_UP));
>                                         ^
> exit status 1

**Comment by pascallanger** [comment]
Thanks, I've added your changes.
Pascal

**Comment by pascallanger** [comment]
The main NFE Silverware fork only list Deviation as an option. Could Multi be added?

**Comment by brianquad** [comment]
Thanks for merging! (And thanks for all the work on this project!!)

Multi is currently an option for NFE Silverware in general and for the Analog Aux stuff (that's what I use). What, exactly, are you looking at where it looks like Multi is missing as an option? I can check it out and clarify.

**Pull request merged**
