### PR TITLE
made pins configurable and added support for nano

### PR DESCRIPTION
**Pull request by bikemike**
I made these changes so I could use my existing diy nrf24_multipro module and was able to get it working.

The changes should be tested with a DIY Multiprotocol TX Module to make sure I didn't break anything.

### CODE REVIEW

**Comment by pascallanger** [comment]
Hi,
There is an issue with at least this statement:
#define TELEMETRY_SERIAL_TX_pin 2
The TX pin is 1 which makes a mask of 2 to set and reset the pin. But with your code the mask is 4...
I need to review further your proposed changes.
- Pascal

**Comment by bikemike** [comment]
Sorry about that. Looks like you got it sorted out though. Thanks!

**Comment by pascallanger** [comment]
There was far more than what I've raised above but yes it's working in the end... Just lost a couple of hours to fix things.
Do you have the pinout handy for the nrf24_multipro module or what needs to be changed to get it working? I can integrate a compile directive so it's easy to get this module working with the multi code. Other wise I'll have a look myself.
Pascal

**Comment by bikemike** [comment]
Sorry to take up so much of your time. I only had my nano and nrf24l01+ to test with.

The following pinout is for the nrf24_multipro. It uses the CE pin as well but I just set that high and it worked fine.

#define PPM_pin   2  // PPM in
//SPI Comm.pins with nRF24L01
#define MOSI_pin  3  // MOSI - D3
#define SCK_pin   4  // SCK  - D4
#define CE_pin    5  // CE   - D5
#define MISO_pin  A0 // MISO - A0
#define CS_pin    A1 // CS   - A1

#define ledPin    13 // LED  - D13


Copied from here:

https://github.com/goebish/nrf24_multipro/blob/master/nRF24_multipro/nRF24_multipro.ino#L36

**Pull request merged**
